import type { ItemDefinition } from "../../simulation/types";

// 020-character-item-pools: Lucien Soto's (Velodrome) 15-item exclusive
// pool. Locked concept list (2026-08-12) after interactive authoring with
// the user. The Needle's pool is deliberately Power-heavy (10 Power / 5
// Chassis), matching its topology. Its four 5cr chase cards anchor cadence,
// late-race sprinting, linked gearing, and lightweight curation; two 4cr
// Chassis pieces are strong general pickups rather than extra archetypes.
// "Cadence" specifically means real cooldown-gated stacking accumulation,
// never a claim that continuously active physics items fire separately.
// Magnitudes use 021's measured sensitivity targets. Fitted/Improvised
// behaviors remain physics-blind, and no item sets legacy identityTag.

const NONE: ItemDefinition["fittedBehavior"] = { kind: "none", description: "Fitted: no additional consequence." };
const NONE_IMPROVISED: ItemDefinition["improvisedBehavior"] = {
  kind: "none",
  description: "Improvised: no additional consequence.",
};
const TIGHT_CORNER = 55;

export const SOTO_ITEMS: readonly ItemDefinition[] = [
  // --- Chase cards (#1-#4), one per build archetype ---
  {
    id: "soto-racing-crankset",
    name: "Racing Crankset",
    price: 5,
    timeModifier: 0,
    origin: "velodrome",
    installationCategory: "power",
    synergyTags: ["momentum", "gearing"],
    buff: { boostPercent: 3, targetStat: "acceleration" },
    cooldown: 2,
    fittedBehavior: NONE,
    improvisedBehavior: NONE_IMPROVISED,
  },
  {
    id: "soto-oversized-drive-sprocket",
    name: "Oversized Drive Sprocket",
    price: 5,
    timeModifier: 0,
    origin: "velodrome",
    installationCategory: "power",
    synergyTags: ["gearing", "momentum"],
    buff: { boostPercent: 2, targetStat: "topSpeed" },
    cooldown: 3,
    fittedBehavior: NONE,
    improvisedBehavior: NONE_IMPROVISED,
  },
  {
    id: "soto-close-ratio-chainwheel-set",
    name: "Close-Ratio Chainwheel Set",
    price: 5,
    timeModifier: 0,
    origin: "velodrome",
    installationCategory: "power",
    synergyTags: ["gearing", "lightweight"],
    physics: { accelerationDelta: 6, topSpeedDelta: 1 },
    synergyEffects: [
      {
        target: { kind: "tag", tag: "gearing" },
        appliesTo: "self",
        condition: { kind: "linear-per-count", percentPerMatch: 8 },
        targetStat: "acceleration",
        description:
          "Synergy: each other gearing part brings the ratios closer — +8% acceleration effect per other gearing-tagged item held.",
      },
      {
        target: { kind: "tag", tag: "gearing" },
        appliesTo: "self",
        condition: { kind: "linear-per-count", percentPerMatch: 8 },
        targetStat: "topSpeed",
        description:
          "Synergy: each other gearing part extends the usable ratio — +8% top-speed effect per other gearing-tagged item held.",
      },
    ],
    fittedBehavior: NONE,
    improvisedBehavior: NONE_IMPROVISED,
  },
  {
    id: "soto-double-butted-tube-frame",
    name: "Double-Butted Tube Frame",
    price: 5,
    timeModifier: 0,
    origin: "velodrome",
    installationCategory: "chassis",
    synergyTags: ["lightweight", "momentum"],
    physics: { corneringSpeedDelta: 3 },
    synergyEffects: [
      {
        target: { kind: "tag", tag: "lightweight" },
        appliesTo: "self",
        condition: { kind: "exact-other-count", count: 2, bonusPercent: 35 },
        targetStat: "corneringSpeed",
        description:
          "Synergy: exactly two other lightweight parts complete the load path — +35% cornering effect.",
      },
    ],
    fittedBehavior: NONE,
    improvisedBehavior: NONE_IMPROVISED,
  },

  // --- Supporting items (#5-#15) ---
  {
    id: "soto-pneumatic-racing-tyres",
    name: "Pneumatic Racing Tyres",
    price: 4,
    timeModifier: 0,
    origin: "velodrome",
    installationCategory: "chassis",
    synergyTags: ["momentum", "lightweight"],
    physics: { corneringSpeedDelta: 3 },
    fittedBehavior: NONE,
    improvisedBehavior: NONE_IMPROVISED,
  },
  {
    id: "soto-tensioned-wire-spoke-wheels",
    name: "Tensioned Wire-Spoke Wheels",
    price: 4,
    timeModifier: 0,
    origin: "velodrome",
    installationCategory: "chassis",
    synergyTags: ["lightweight", "wheel"],
    physics: { accelerationDelta: 13 },
    fittedBehavior: NONE,
    improvisedBehavior: NONE_IMPROVISED,
  },
  {
    id: "soto-hollow-steel-fork",
    name: "Hollow Steel Fork",
    price: 2,
    timeModifier: 0,
    origin: "velodrome",
    installationCategory: "chassis",
    synergyTags: ["lightweight", "momentum"],
    physics: { corneringSpeedDelta: 1 },
    fittedBehavior: NONE,
    improvisedBehavior: NONE_IMPROVISED,
  },
  {
    id: "soto-cable-operated-rim-brake",
    name: "Cable-Operated Rim Brake",
    price: 2,
    timeModifier: 0,
    origin: "velodrome",
    installationCategory: "chassis",
    synergyTags: ["lightweight", "gearing"],
    physics: { brakingPowerDelta: 13 },
    fittedBehavior: NONE,
    improvisedBehavior: NONE_IMPROVISED,
  },
  {
    id: "soto-roller-link-drive-chain",
    name: "Roller-Link Drive Chain",
    price: 4,
    timeModifier: 0,
    origin: "velodrome",
    installationCategory: "power",
    synergyTags: ["gearing", "momentum"],
    physics: { accelerationDelta: 13 },
    fittedBehavior: NONE,
    improvisedBehavior: NONE_IMPROVISED,
  },
  {
    id: "soto-ratchet-freewheel",
    name: "Ratchet Freewheel",
    price: 4,
    timeModifier: 0,
    origin: "velodrome",
    installationCategory: "power",
    synergyTags: ["momentum", "gearing"],
    conditionalPhysics: [
      {
        condition: { kind: "corner-tightness", direction: "at-least", turnDegrees: TIGHT_CORNER },
        delta: { accelerationDelta: 13 },
      },
    ],
    fittedBehavior: NONE,
    improvisedBehavior: NONE_IMPROVISED,
  },
  {
    id: "soto-chain-tensioner",
    name: "Chain Tensioner",
    price: 2,
    timeModifier: 0,
    origin: "velodrome",
    installationCategory: "power",
    synergyTags: ["gearing", "information"],
    physics: { topSpeedDelta: 1 },
    fittedBehavior: NONE,
    improvisedBehavior: NONE_IMPROVISED,
  },
  {
    id: "soto-hand-pump-pressure-gauge",
    name: "Hand Pump and Pressure Gauge",
    price: 4,
    timeModifier: 0,
    origin: "velodrome",
    installationCategory: "power",
    synergyTags: ["information", "lightweight"],
    buff: { boostPercent: 15, targetStat: "corneringSpeed" },
    fittedBehavior: NONE,
    improvisedBehavior: NONE_IMPROVISED,
  },
  {
    id: "soto-two-speed-drive-hub",
    name: "Two-Speed Drive Hub",
    price: 4,
    timeModifier: 0,
    origin: "velodrome",
    installationCategory: "power",
    synergyTags: ["gearing", "momentum"],
    physics: { accelerationDelta: 6, topSpeedDelta: 1 },
    fittedBehavior: NONE,
    improvisedBehavior: NONE_IMPROVISED,
  },
  {
    id: "soto-kick-start-chainring",
    name: "Kick-Start Chainring",
    price: 2,
    timeModifier: 0,
    origin: "velodrome",
    installationCategory: "power",
    synergyTags: ["gearing", "momentum"],
    physics: { accelerationDelta: 6 },
    fittedBehavior: NONE,
    improvisedBehavior: NONE_IMPROVISED,
  },
  {
    id: "soto-engine-drive-pulley",
    name: "Engine Drive Pulley",
    price: 2,
    timeModifier: 0,
    origin: "velodrome",
    installationCategory: "power",
    synergyTags: ["gearing", "momentum"],
    physics: { topSpeedDelta: 1 },
    fittedBehavior: NONE,
    improvisedBehavior: NONE_IMPROVISED,
  },
];
