import Phaser from "phaser";
import type { CarResult, NCarContestResult, OfferedItem } from "../simulation/types";
import type { Run } from "../simulation/run";
import {
  gapLabel,
  outcomeColor,
  outcomeLabel,
  standingsRow,
  timesLabel,
} from "./resultFormatting";
import { createItemCard, enableItemTooltip } from "./itemVisuals";
import { continueRunFromResult } from "./runPresentation";
import {
  addDemoBackdrop,
  addRunStamp,
  createDemoButton,
  DISPLAY_FONT,
  UI_FONT,
} from "./demoTheme";

const STANDINGS_ROW_HEIGHT = 13;

/**
 * Result view. User Story 1 established the outcome banner; User Story 2
 * (T016-T017) added the legibility data below it (FR-006, FR-007);
 * 012-multi-ghost-contest extended it to the full N-car ranked standings
 * (SC-003). All text content is generated by resultFormatting.ts's pure
 * functions, which carry the actual test coverage for this scene
 * (tests/integration/result-scene.test.ts).
 */
export class ResultScene extends Phaser.Scene {
  private result!: NCarContestResult;
  private run!: Run;
  private encounterId!: string;

  constructor() {
    super("ResultScene");
  }

  create(data: { result?: NCarContestResult; run?: Run; encounterId?: string }): void {
    if (!data.result || !data.run || !data.encounterId) {
      this.scene.start("RunScene", { unavailable: true });
      return;
    }
    this.result = data.result;
    this.run = data.run;
    this.encounterId = data.encounterId;
    const { width } = this.scale;
    addDemoBackdrop(this, "race-day", 0.73);
    addRunStamp(this, this.run);

    this.add
      .text(width / 2, 42, outcomeLabel(this.result), {
        fontSize: "26px",
        fontFamily: DISPLAY_FONT,
        fontStyle: "bold",
        color: outcomeColor(this.result),
      })
      .setOrigin(0.5);

    this.renderDetails(width);

    createDemoButton(this, width / 2, 402, "CONTINUE CHAMPIONSHIP", () => {
      const run = continueRunFromResult(this.run, this.encounterId, this.result);
      this.scene.start("RunScene", { run });
    });
  }

  private renderDetails(width: number): void {
    this.add
      .text(width / 2, 68, timesLabel(this.result), { fontSize: "15px", color: "#ffffff" })
      .setFontFamily(UI_FONT)
      .setOrigin(0.5);

    this.add
      .text(width / 2, 88, gapLabel(this.result), {
        fontSize: "13px",
        fontFamily: UI_FONT,
        color: "#cccccc",
      })
      .setOrigin(0.5);

    this.renderStandings(width, 106);
    this.renderItemRow(width * 0.27, 250, "INSTALLED", this.result.board, "#ffdd77");
    this.renderItemRow(width * 0.73, 250, "WORKSHOP STORAGE", this.result.storage, "#8fd8ff");
  }

  private renderStandings(width: number, startY: number): void {
    this.result.cars.forEach((car, index) => {
      const isPlayer = car.role === "player";
      this.add
        .text(width / 2, startY + index * STANDINGS_ROW_HEIGHT, standingsRow(car), {
          fontSize: "11px",
          fontFamily: UI_FONT,
          fontStyle: isPlayer ? "bold" : "normal",
          color: isPlayer ? "#ffd447" : this.rivalRowColor(car),
        })
        .setOrigin(0.5);
    });
  }

  private rivalRowColor(car: CarResult): string {
    return car.color || "#cccccc";
  }

  private renderItemRow(
    centerX: number,
    y: number,
    label: string,
    items: OfferedItem[],
    color: string,
  ): void {
    this.add.text(centerX, y, label, {
      fontSize: "13px",
      fontFamily: UI_FONT,
      fontStyle: "bold",
      color,
    }).setOrigin(0.5);
    if (items.length === 0) {
      this.add.text(centerX, y + 42, "None", { fontSize: "12px", color: "#71808a" }).setOrigin(0.5);
      return;
    }

    const spacing = 104;
    const startX = centerX - ((items.length - 1) * spacing) / 2;
    items.forEach((item, index) => {
      const card = createItemCard(this, startX + index * spacing, y + 48, item, {
        width: 96,
        height: 82,
        iconSize: 44,
        layout: "column",
      }).setInteractive({ useHandCursor: true });
      enableItemTooltip(this, card, item);
    });
  }
}
