import Phaser from "phaser";
import type { ContestResult } from "../simulation/types";
import {
  boardItemsLabel,
  gapLabel,
  outcomeColor,
  outcomeLabel,
  storageItemsLabel,
  timesLabel,
} from "./resultFormatting";

/**
 * Result view. User Story 1 established the outcome banner; User Story 2
 * (T016-T017) added the legibility data below it (FR-006, FR-007). All
 * text content is generated by resultFormatting.ts's pure functions, which
 * carry the actual test coverage for this scene (tests/integration/result-scene.test.ts).
 */
export class ResultScene extends Phaser.Scene {
  private result!: ContestResult;

  constructor() {
    super("ResultScene");
  }

  create(data: { result: ContestResult }): void {
    this.result = data.result;
    const { width } = this.scale;

    this.add
      .text(width / 2, 80, outcomeLabel(this.result), {
        fontSize: "32px",
        color: outcomeColor(this.result),
      })
      .setOrigin(0.5);

    this.renderDetails(width);

    const again = this.add
      .text(width / 2, 380, "Race Again", {
        fontSize: "18px",
        color: "#ffffff",
        backgroundColor: "#333333",
        padding: { x: 16, y: 8 },
      })
      .setOrigin(0.5)
      .setInteractive({ useHandCursor: true });

    again.on("pointerdown", () => this.scene.start("PrepareScene"));
  }

  private renderDetails(width: number): void {
    this.add
      .text(width / 2, 150, timesLabel(this.result), { fontSize: "18px", color: "#ffffff" })
      .setOrigin(0.5);

    this.add
      .text(width / 2, 185, `Gap: ${gapLabel(this.result)}`, {
        fontSize: "16px",
        color: "#cccccc",
      })
      .setOrigin(0.5);

    this.add
      .text(width * 0.27, 235, boardItemsLabel(this.result), {
        fontSize: "13px",
        color: "#ffdd77",
        wordWrap: { width: width * 0.44 },
        align: "center",
      })
      .setOrigin(0.5, 0);

    this.add
      .text(width * 0.73, 235, storageItemsLabel(this.result), {
        fontSize: "13px",
        color: "#8fd8ff",
        wordWrap: { width: width * 0.44 },
        align: "center",
      })
      .setOrigin(0.5, 0);
  }
}
