import Phaser from "phaser";
import type { CarResult, NCarContestResult, OfferedItem } from "../simulation/types";
import type { Run } from "../simulation/run";
import {
  carSetupLines,
  gapLabel,
  outcomeColor,
  outcomeLabel,
  playerCar,
  standingsRow,
  timesLabel,
  runRecordLabel,
} from "./resultFormatting";
import { createItemCard, createItemInspector } from "./itemVisuals";
import { resolvedItemEvidence, type ItemPresentationContext } from "./itemPresentation";
import { continueRunFromResult } from "./runPresentation";
import {
  addDemoBackdrop,
  addRunStamp,
  createDemoButton,
  DISPLAY_FONT,
  UI_FONT,
} from "./demoTheme";
import { configureHiDpiScene, LOGICAL_WIDTH } from "./layout";
import { recordedLapVehicleStatModel } from "./vehicleStatPresentation";
import { createVehicleStatPanel } from "./vehicleStatVisuals";
import { buildTrackFitPresentation } from "./trackSummaryPresentation";
import { createBuildTrackFitPanel } from "./trackFitVisuals";
import { regionDefinition } from "../content/regions";
import { classifyScalingItem } from "../simulation/buffs";

const STANDINGS_ROW_HEIGHT = 13;

/**
 * Result view. User Story 1 established the outcome banner; User Story 2
 * (T016-T017) added the legibility data below it (FR-006, FR-007);
 * 012-multi-ghost-contest extended it to the full N-car ranked standings
 * (SC-003). All text content is generated by resultFormatting.ts's pure
 * functions, which carry the actual test coverage for this scene
 * (tests/integration/result-scene.test.ts).
 */
export class ResultScene extends Phaser.Scene {
  private result!: NCarContestResult;
  private run!: Run;
  private encounterId!: string;
  private selectedItem?: OfferedItem;
  private itemInspector?: Phaser.GameObjects.Container;

  constructor() {
    super("ResultScene");
  }

  create(data: { result?: NCarContestResult; run?: Run; encounterId?: string }): void {
    configureHiDpiScene(this);
    if (!data.result || !data.run || !data.encounterId) {
      this.scene.start("RunScene", { unavailable: true });
      return;
    }
    this.result = data.result;
    this.run = data.run;
    this.encounterId = data.encounterId;
    const width = LOGICAL_WIDTH;
    addDemoBackdrop(this, "scene-finish-line", 0.6);
    // Credits are not actionable on Results and the top-right space belongs to
    // the build–track comparison legend. Keep the useful stage stamp only.
    addRunStamp(this, this.run, { showCredits: false });
    const stage = this.run.stages[this.run.stageIndex];
    if (stage?.regionId) {
      this.add.text(width / 2, 18, `${regionDefinition(stage.regionId).name} · ${stage.raceKind === "local" ? "LOCAL RACE" : "CHAMPIONSHIP RACE"}`, {
        fontSize: "11px", fontFamily: UI_FONT, fontStyle: "bold", color: "#cddbd2",
      }).setOrigin(0.5);
    }

    this.add
      .text(width * 0.24, 42, outcomeLabel(this.result), {
        fontSize: "26px",
        fontFamily: DISPLAY_FONT,
        fontStyle: "bold",
        color: outcomeColor(this.result),
      })
      .setOrigin(0.5);

    this.renderDetails(width);
    this.renderScalingEvidence(width);
    this.add.text(width * 0.76, 228, runRecordLabel(this.run), {
      fontSize: "11px", fontFamily: UI_FONT, fontStyle: "bold", color: "#ffd447",
    }).setOrigin(0.5);
    this.renderSetupEvidence(width);

    createDemoButton(this, width / 2, 402, "CONTINUE CHAMPIONSHIP", () => {
      const run = continueRunFromResult(this.run, this.encounterId, this.result);
      this.scene.start("RunScene", { run });
    });
    createDemoButton(this, width - 70, 382, "INVENTORY", () => this.scene.start("InventoryScene", {
      run: this.run, host: "result", returnScene: "ResultScene",
      returnData: { result: this.result, encounterId: this.encounterId },
    }), true, { fontSize: "10px", width: 112, height: 30 });
  }

  private renderDetails(width: number): void {
    this.add
      .text(width * 0.24, 68, timesLabel(this.result), { fontSize: "15px", color: "#ffffff" })
      .setFontFamily(UI_FONT)
      .setOrigin(0.5);

    this.add
      .text(width * 0.24, 88, gapLabel(this.result), {
        fontSize: "13px",
        fontFamily: UI_FONT,
        color: "#cccccc",
      })
      .setOrigin(0.5);

    this.renderStandings(width * 0.24, 106);
    this.renderBuildTrackFit(width);
    this.renderVehicleStatPanel(width);
    this.renderItemRow(width * 0.24, 296, "INSTALLED", this.result.board, "#d7e4e7");
    this.renderItemRow(width * 0.76, 338, "WORKSHOP STORAGE", this.result.storage, "#8fd8ff");
  }

  /**
   * The exact generated track's composition (027-race-legibility-integrity
   * US4) — read from `result.track` only, never regenerated. Placed beside
   * the centered standings list, the one genuinely free column in this
   * scene's layout (contract §6: Results MUST NOT call generateTrack;
   * FR-019: missing/malformed evidence is labeled, not inferred).
   */
  private renderBuildTrackFit(width: number): void {
    createBuildTrackFitPanel(
      this,
      width * 0.49,
      18,
      buildTrackFitPresentation(this.result),
      { width: width * 0.49, height: 238 },
    ).setDepth(18);
  }

  /**
   * The player's effective four-stat profile for the final completed lap
   * (025-vehicle-stat-display US3) — same recorded-evidence model and
   * shared renderer as ContestScene/TestDayScene, using the final lap as
   * this scene's one completed-lap inspection context (contract §5).
   */
  private renderVehicleStatPanel(width: number): void {
    const player = this.result.cars.find((car) => car.role === "player");
    const lapIndex = Math.max(0, (player?.laps.length ?? 1) - 1);
    const lap = player?.laps[lapIndex];
    const lookup = new Map([...this.result.board, ...this.result.storage].map((item) => [item.id, item] as const));
    const model = recordedLapVehicleStatModel({
      lap: lapIndex + 1,
      lapCount: this.result.lapCount,
      contextKind: "result-lap",
      physics: lap?.physics,
      itemLookup: lookup,
    });
    this.add.text(width * 0.51, 260, "YOUR VEHICLE", {
      fontSize: "10px", fontFamily: UI_FONT, fontStyle: "bold", color: "#8fd8ff",
    }).setDepth(20);
    createVehicleStatPanel(this, width * 0.745, 292, model, {
      viewport: { width: width * 0.48, height: 60 },
    }).setDepth(20);
  }

  private renderScalingEvidence(width: number): void {
    const installed = this.result.board;
    const evidence = [...this.result.board, ...this.result.storage]
      .map((item) => classifyScalingItem(item, { heldItems: [...this.result.board, ...this.result.storage], installedItems: installed }))
      .filter((entry): entry is NonNullable<typeof entry> => entry !== null);
    if (evidence.length === 0) return;
    this.add.text(width * 0.76, 286, evidence.map((entry) =>
      `${entry.kind.toUpperCase()} · input ${entry.currentInput} · ${entry.currentMagnitude}%\n${entry.nextTriggerLabel}`,
    ).join("\n"), { fontSize: "8px", fontFamily: UI_FONT, color: "#d7e4e7", wordWrap: { width: width * 0.42 } }).setOrigin(0.5, 0);
  }

  /**
   * 028-pre-race-setup contract §10: reads the player's own `CarResult.setup`
   * only — never infers or regenerates a setting. Missing evidence (a
   * pre-028 legacy result) renders the explicit unavailable label.
   */
  private renderSetupEvidence(width: number): void {
    const player = playerCar(this.result);
    this.add.text(width * 0.76, 246, carSetupLines(player).join("\n"), {
      fontSize: "10px", fontFamily: UI_FONT, color: "#ffd447", lineSpacing: 3,
    }).setOrigin(0.5, 0);
  }

  private renderStandings(centerX: number, startY: number): void {
    this.result.cars.forEach((car, index) => {
      const isPlayer = car.role === "player";
      this.add
        .text(centerX, startY + index * STANDINGS_ROW_HEIGHT, standingsRow(car), {
          fontSize: "11px",
          fontFamily: UI_FONT,
          fontStyle: isPlayer ? "bold" : "normal",
          color: isPlayer ? "#ffd447" : this.rivalRowColor(car),
        })
        .setOrigin(0.5);
    });
  }

  private rivalRowColor(car: CarResult): string {
    return car.color || "#cccccc";
  }

  private renderItemRow(
    centerX: number,
    y: number,
    label: string,
    items: OfferedItem[],
    color: string,
  ): void {
    this.add.text(centerX, y, label, {
      fontSize: "13px",
      fontFamily: UI_FONT,
      fontStyle: "bold",
      color,
    }).setOrigin(0.5);
    if (items.length === 0) {
      this.add.text(centerX, y + 42, "None", { fontSize: "12px", color: "#71808a" }).setOrigin(0.5);
      return;
    }

    const availableWidth = 350;
    const gap = 8;
    const cardWidth = Math.min(140, Math.floor((availableWidth - gap * (items.length - 1)) / items.length));
    const spacing = cardWidth + gap;
    const startX = centerX - ((items.length - 1) * spacing) / 2;
    items.forEach((item, index) => {
      const card = createItemCard(this, startX + index * spacing, y + 48, item, {
        width: cardWidth,
        height: 82,
        iconSize: 44,
        layout: "column",
      }).setInteractive({ useHandCursor: true });
      card.on("pointerdown", () => {
        this.selectedItem = item;
        this.renderItemInspector();
      });
    });
  }

  private renderItemInspector(): void {
    this.itemInspector?.destroy();
    const player = this.result.cars.find((car) => car.role === "player");
    const lap = player?.laps[player.laps.length - 1];
    const physical = lap?.physics?.itemContributions?.find((entry) => entry.sourceItemId === this.selectedItem?.id);
    const context: ItemPresentationContext = {
      surface: "result",
      tier: physical?.tier ?? 1,
      lapEvidence: this.selectedItem && physical
        ? resolvedItemEvidence(this.selectedItem, { kind: "physical", evidence: physical }) : undefined,
    };
    if (!this.selectedItem) return;
    this.itemInspector = createItemInspector(this, LOGICAL_WIDTH / 2, 350, this.selectedItem, context, {
      width: LOGICAL_WIDTH - 48, height: 84,
    }).setDepth(80);
  }
}
